dist: bionic
language: php
php:
    - '7.4'
script: 
    - vendor/bin/phpunit
    - vendor/bin/phpcs --ignore=*/Themes/* --standard=PSR1,PSR2,PSR12 src
    - vendor/bin/phpstan analyse src --level 8
install: composer install
cache:
    directories:
      - node_modules
      - vendor
