#!/usr/bin/env php
<?php declare(strict_types=1);

/*
 * This file is part of MarkHelp.
 *
 * (c) Ricardo Pereira <contato@ricardopdias.com.br>
 *
 * For the full copyright and license information, please view the licence.md
 * file that was distributed with this source code.
 */

use MarkHelp\Console\Cli;

define('APP_START', microtime(true));

if (version_compare('7.2.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of MarkHelp is supported on PHP 7.2, PHP 7.3, and PHP 7.4.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

$locations = [__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'];
foreach ($locations as $file) {
    if (file_exists($file)) {
        define('MARKHELP_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('MARKHELP_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require MARKHELP_COMPOSER_INSTALL;

(new Cli)
    ->loadVersionFrom(__DIR__ . DIRECTORY_SEPARATOR . 'version.app')
    ->run();